[package]
name = "lnqft"
version = "0.1.0-alpha.2"
authors = ["angsy <65333430+angsy@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
